export * from './home/home.component';
export * from './team/team.component';
export * from './events/events.component';
export * from './services/services.component';
export * from './signup/signup.component';
export * from './contact/contact.component';
export * from './guide/guide.component';
export * from './dsc/dsc.component';
export * from './exec-applications/execapplications.component';
